### ISSUE TITLE
`ImportError: cannot import name 'url_decode' from 'werkzeug.urls'` after upgrading `werkzeug` to 3.0.0

### ISSUE THREAD

**Issue by globau** [maxcountryman/flask-login#803]
flask-login no long works after upgrading to `werkzeug` 3.0.0 

```
Traceback (most recent call last):
  File "src/web.py", line 8, in <module>
    import auth
  File "src/auth.py", line 5, in <module>
    import flask_login
  File "venv/lib/python3.11/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "venv/lib/python3.11/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (venv/lib/python3.11/site-packages/werkzeug/urls.py)
```

As per https://werkzeug.palletsprojects.com/en/3.0.x/changes/, deprecated features were removed via https://github.com/pallets/werkzeug/pull/2768
This includes:
> Remove our copy of `urllib.parse` from our `urls` module, in favor of using the built-in module directly

`url.py` was deprecated in werkzeug 2.3.0 via https://github.com/pallets/werkzeug/commit/d4ddff63fad160c1e5ab101c7eb5103bef9a101e

**Comment by globau** [comment]
Oops, looks like this is a duplicate of #744, which doesn't appear to be in a release yet.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
